import Head from "next/head";

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta content="Generated by create next app" name="description" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link href="/favicon.ico" rel="icon" />
    </Head>

    <main>
      <div>
        <h1>asdasd</h1>
      </div>
    </main>
  </>
);

export default Home;
